### PR TITLE
Ensure monitor nodes have the keyring in place

### PR DESCRIPTION
**Pull request by cityofships**

### CODE REVIEW

**Review by mnasiadka — CHANGES_REQUESTED** [review]
At least a link to docs that describe what this label does (in the commit message)?

**Review by markgoddard — APPROVED** [review]

**Comment by cityofships** [comment]
Docs now included.
https://docs.ceph.com/en/latest/cephadm/install/#running-the-bootstrap-command
https://docs.ceph.com/en/latest/cephadm/install/#adding-hosts

**Review by mnasiadka — APPROVED** [review]

**Comment by markgoddard** [comment]
This repo needs some CI

**Comment by mnasiadka** [comment]
Yes, it does - but now we're busy using this code ;-) I have that planned for the ,,calm'' Christmas-new year period.

**Pull request merged**
